# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AdPagesGo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AdPagesGo

  pod 'OneSignal', '~> 1.13.3'
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'

end
